name: CI

on:
  push:
    branches:
      - feature/lab2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.8
          distribution: 'adopt'  # Specify the distribution you want (e.g., 'adopt', 'adopt-hotspot', 'adopt-openj9')

      - name: Grant execute permissions to gradlew script
        run: chmod +x ./gradlew


      - name: Build with Gradle
        run: ./gradlew build

      - name: Run JUnit tests
        run: ./gradlew test
